const express = require("express");
const app = express();
const path = require("path");
const cookieParser = require("cookie-parser");
const userModel = require("./models/user");
const postModel = require("./models/post");
const bcrypt = require("bcrypt");
const jwt = require("jsonwebtoken");

const distances = {
  "Lahore Thokar:Lahore Kalma Chowk": 599,
  "Lahore Kalma Chowk:Lahore Thokar": 599,
  "Lahore Thokar:Rawalpindi": 658,
  "Rawalpindi:Lahore Thokar": 658,
  "Lahore Thokar:Faisalabad": 237,
  "Faisalabad:Lahore Thokar": 237,
  "Lahore Thokar:Gultan": 1187,
  "Gultan:Lahore Thokar": 1187,
  "Lahore Thokar:Sargodha": 270,
  "Sargodha:Lahore Thokar": 270,
  "Lahore Thokar:Abbottabad": 216,
  "Abbottabad:Lahore Thokar": 216,
  "Lahore Thokar:Faizabad": 1380,
  "Faizabad:Lahore Thokar": 1380,
  "Lahore Thokar:Bahawalpur": 774,
  "Bahawalpur:Lahore Thokar": 774,
  "Lahore Thokar:Hakar Chowk": 261,
  "Hakar Chowk:Lahore Thokar": 261,
  "Lahore Thokar:Bahadurpur Chowk": 750,
  "Bahadurpur Chowk:Lahore Thokar": 750,
  "Lahore Thokar:Chichawatni": 143,
  "Chichawatni:Lahore Thokar": 143,
  "Lahore Thokar:Daska": 201,
  "Daska:Lahore Thokar": 201,
  "Lahore Thokar:Gujranwala": 1475,
  "Gujranwala:Lahore Thokar": 1475,
  "Lahore Thokar:Gujrat": 1076,
  "Gujrat:Lahore Thokar": 1076,
  "Lahore Thokar:Hyderabad": 922,
  "Hyderabad:Lahore Thokar": 922,
  "Lahore Thokar:Jhang": 164,
  "Jhang:Lahore Thokar": 164,
  "Lahore Thokar:Jhelum": 1130,
  "Jhelum:Lahore Thokar": 1130,
  "Lahore Thokar:Ranipur": 989,
  "Ranipur:Lahore Thokar": 989,
  "Lahore Thokar:Karachi": 296,
  "Karachi:Lahore Thokar": 296,
  "Lahore Thokar:Karachi Cantt": 133,
  "Karachi Cantt:Lahore Thokar": 133,
  "Lahore Thokar:Kohat": 1186,
  "Kohat:Lahore Thokar": 1186,
  "Lahore Thokar:Murree": 394,
  "Murree:Lahore Thokar": 394,
  "Lahore Thokar:Okara Cantt": 645,
  "Okara Cantt:Lahore Thokar": 645,
  "Lahore Thokar:Okara City": 156,
  "Okara City:Lahore Thokar": 156,
  "Lahore Thokar:Sahiwal": 170,
  "Sahiwal:Lahore Thokar": 170,
  "Lahore Thokar:Multan": 300,
  "Multan:Lahore Thokar": 300,
  "Lahore Thokar:Vehari Chowk": 385,
  "Vehari Chowk:Lahore Thokar": 385,
  "Lahore Thokar:Peshawar": 1105,
  "Peshawar:Lahore Thokar": 1105,
  "Lahore Thokar:Islamabad": 606,
  "Islamabad:Lahore Thokar": 606,
  "Lahore Thokar:Quetta": 1025,
  "Quetta:Lahore Thokar": 1025,
  "Lahore Thokar:Sialkot": 1173,
  "Sialkot:Lahore Thokar": 1173,
  "Lahore Kalma Chowk:Rawalpindi": 907,
  "Rawalpindi:Lahore Kalma Chowk": 907,
  "Lahore Kalma Chowk:Faisalabad": 525,
  "Faisalabad:Lahore Kalma Chowk": 525,
  "Lahore Kalma Chowk:Gultan": 213,
  "Gultan:Lahore Kalma Chowk": 213,
  "Lahore Kalma Chowk:Sargodha": 563,
  "Sargodha:Lahore Kalma Chowk": 563,
  "Lahore Kalma Chowk:Abbottabad": 147,
  "Abbottabad:Lahore Kalma Chowk": 147,
  "Lahore Kalma Chowk:Faizabad": 690,
  "Faizabad:Lahore Kalma Chowk": 690,
  "Lahore Kalma Chowk:Bahawalpur": 689,
  "Bahawalpur:Lahore Kalma Chowk": 689,
  "Lahore Kalma Chowk:Hakar Chowk": 975,
  "Hakar Chowk:Lahore Kalma Chowk": 975,
  "Lahore Kalma Chowk:Bahadurpur Chowk": 1410,
  "Bahadurpur Chowk:Lahore Kalma Chowk": 1410,
  "Lahore Kalma Chowk:Chichawatni": 872,
  "Chichawatni:Lahore Kalma Chowk": 872,
  "Lahore Kalma Chowk:Daska": 289,
  "Daska:Lahore Kalma Chowk": 289,
  "Lahore Kalma Chowk:Gujranwala": 771,
  "Gujranwala:Lahore Kalma Chowk": 771,
  "Lahore Kalma Chowk:Gujrat": 1016,
  "Gujrat:Lahore Kalma Chowk": 1016,
  "Lahore Kalma Chowk:Hyderabad": 157,
  "Hyderabad:Lahore Kalma Chowk": 157,
  "Lahore Kalma Chowk:Jhang": 266,
  "Jhang:Lahore Kalma Chowk": 266,
  "Lahore Kalma Chowk:Jhelum": 1174,
  "Jhelum:Lahore Kalma Chowk": 1174,
  "Lahore Kalma Chowk:Ranipur": 671,
  "Ranipur:Lahore Kalma Chowk": 671,
  "Lahore Kalma Chowk:Karachi": 829,
  "Karachi:Lahore Kalma Chowk": 829,
  "Lahore Kalma Chowk:Karachi Cantt": 1114,
  "Karachi Cantt:Lahore Kalma Chowk": 1114,
  "Lahore Kalma Chowk:Kohat": 1213,
  "Kohat:Lahore Kalma Chowk": 1213,
  "Lahore Kalma Chowk:Murree": 1252,
  "Murree:Lahore Kalma Chowk": 1252,
  "Lahore Kalma Chowk:Okara Cantt": 154,
  "Okara Cantt:Lahore Kalma Chowk": 154,
  "Lahore Kalma Chowk:Okara City": 156,
  "Okara City:Lahore Kalma Chowk": 156,
  "Lahore Kalma Chowk:Sahiwal": 170,
  "Sahiwal:Lahore Kalma Chowk": 170,
  "Lahore Kalma Chowk:Multan": 882,
  "Multan:Lahore Kalma Chowk": 882,
  "Lahore Kalma Chowk:Vehari Chowk": 882,
  "Vehari Chowk:Lahore Kalma Chowk": 882,
  "Lahore Kalma Chowk:Peshawar": 953,
  "Peshawar:Lahore Kalma Chowk": 953,
  "Lahore Kalma Chowk:Islamabad": 1072,
  "Islamabad:Lahore Kalma Chowk": 1072,
  "Lahore Kalma Chowk:Quetta": 1498,
  "Quetta:Lahore Kalma Chowk": 1498,
  "Lahore Kalma Chowk:Sialkot": 1238,
  "Sialkot:Lahore Kalma Chowk": 1238,
  "Rawalpindi:Faisalabad": 1099,
  "Faisalabad:Rawalpindi": 1099,
  "Rawalpindi:Gultan": 101,
  "Gultan:Rawalpindi": 101,
  "Rawalpindi:Sargodha": 1091,
  "Sargodha:Rawalpindi": 1091,
  "Rawalpindi:Abbottabad": 876,
  "Abbottabad:Rawalpindi": 876,
  "Rawalpindi:Faizabad": 951,
  "Faizabad:Rawalpindi": 951,
  "Rawalpindi:Bahawalpur": 1074,
  "Bahawalpur:Rawalpindi": 1074,
  "Rawalpindi:Hakar Chowk": 54,
  "Hakar Chowk:Rawalpindi": 54,
  "Rawalpindi:Bahadurpur Chowk": 603,
  "Bahadurpur Chowk:Rawalpindi": 603,
  "Rawalpindi:Chichawatni": 153,
  "Chichawatni:Rawalpindi": 153,
  "Rawalpindi:Daska": 625,
  "Daska:Rawalpindi": 625,
  "Rawalpindi:Gujranwala": 835,
  "Gujranwala:Rawalpindi": 835,
  "Rawalpindi:Gujrat": 1441,
  "Gujrat:Rawalpindi": 1441,
  "Rawalpindi:Hyderabad": 1038,
  "Hyderabad:Rawalpindi": 1038,
  "Rawalpindi:Jhang": 753,
  "Jhang:Rawalpindi": 753,
  "Rawalpindi:Jhelum": 1440,
  "Jhelum:Rawalpindi": 1440,
  "Rawalpindi:Ranipur": 298,
  "Ranipur:Rawalpindi": 298,
  "Rawalpindi:Karachi": 433,
  "Karachi:Rawalpindi": 433,
  "Rawalpindi:Karachi Cantt": 1169,
  "Karachi Cantt:Rawalpindi": 1169,
  "Rawalpindi:Kohat": 1287,
  "Kohat:Rawalpindi": 1287,
  "Rawalpindi:Murree": 106,
  "Murree:Rawalpindi": 106,
  "Rawalpindi:Okara Cantt": 1142,
  "Okara Cantt:Rawalpindi": 1142,
  "Rawalpindi:Okara City": 109,
  "Okara City:Rawalpindi": 109,
  "Rawalpindi:Sahiwal": 212,
  "Sahiwal:Rawalpindi": 212,
  "Rawalpindi:Multan": 890,
  "Multan:Rawalpindi": 890,
  "Rawalpindi:Vehari Chowk": 1152,
  "Vehari Chowk:Rawalpindi": 1152,
  "Rawalpindi:Peshawar": 1334,
  "Peshawar:Rawalpindi": 1334,
  "Rawalpindi:Islamabad": 452,
  "Islamabad:Rawalpindi": 452,
  "Rawalpindi:Quetta": 910,
  "Quetta:Rawalpindi": 910,
  "Rawalpindi:Sialkot": 1196,
  "Sialkot:Rawalpindi": 1196,
  "Faisalabad:Gultan": 1472,
  "Gultan:Faisalabad": 1472,
  "Faisalabad:Sargodha": 1354,
  "Sargodha:Faisalabad": 1354,
  "Faisalabad:Abbottabad": 337,
  "Abbottabad:Faisalabad": 337,
  "Faisalabad:Faizabad": 1449,
  "Faizabad:Faisalabad": 1449,
  "Faisalabad:Bahawalpur": 1249,
  "Bahawalpur:Faisalabad": 1249,
  "Faisalabad:Hakar Chowk": 478,
  "Hakar Chowk:Faisalabad": 478,
  "Faisalabad:Bahadurpur Chowk": 1315,
  "Bahadurpur Chowk:Faisalabad": 1315,
  "Faisalabad:Chichawatni": 603,
  "Chichawatni:Faisalabad": 603,
  "Faisalabad:Daska": 925,
  "Daska:Faisalabad": 925,
  "Faisalabad:Gujranwala": 394,
  "Gujranwala:Faisalabad": 394,
  "Faisalabad:Gujrat": 948,
  "Gujrat:Faisalabad": 948,
  "Faisalabad:Hyderabad": 1466,
  "Hyderabad:Faisalabad": 1466,
  "Faisalabad:Jhang": 1179,
  "Jhang:Faisalabad": 1179,
  "Faisalabad:Jhelum": 647,
  "Jhelum:Faisalabad": 647,
  "Faisalabad:Ranipur": 1193,
  "Ranipur:Faisalabad": 1193,
  "Faisalabad:Karachi": 108,
  "Karachi:Faisalabad": 108,
  "Faisalabad:Karachi Cantt": 1109,
  "Karachi Cantt:Faisalabad": 1109,
  "Faisalabad:Kohat": 657,
  "Kohat:Faisalabad": 657,
  "Faisalabad:Murree": 696,
  "Murree:Faisalabad": 696,
  "Faisalabad:Okara Cantt": 766,
  "Okara Cantt:Faisalabad": 766,
  "Faisalabad:Okara City": 669,
  "Okara City:Faisalabad": 669,
  "Faisalabad:Sahiwal": 1442,
  "Sahiwal:Faisalabad": 1442,
  "Faisalabad:Multan": 321,
  "Multan:Faisalabad": 321,
  "Faisalabad:Vehari Chowk": 66,
  "Vehari Chowk:Faisalabad": 66,
  "Faisalabad:Peshawar": 577,
  "Peshawar:Faisalabad": 577,
  "Faisalabad:Islamabad": 734,
  "Islamabad:Faisalabad": 734,
  "Faisalabad:Quetta": 1441,
  "Quetta:Faisalabad": 1441,
  "Faisalabad:Sialkot": 226,
  "Sialkot:Faisalabad": 226,
  "Gultan:Sargodha": 892,
  "Sargodha:Gultan": 892,
  "Gultan:Abbottabad": 357,
  "Abbottabad:Gultan": 357,
  "Gultan:Faizabad": 1412,
  "Faizabad:Gultan": 1412,
  "Gultan:Bahawalpur": 1407,
  "Bahawalpur:Gultan": 1407,
  "Gultan:Hakar Chowk": 491,
  "Hakar Chowk:Gultan": 491,
  "Gultan:Bahadurpur Chowk": 1112,
  "Bahadurpur Chowk:Gultan": 1112,
  "Gultan:Chichawatni": 839,
  "Chichawatni:Gultan": 839,
  "Gultan:Daska": 1154,
  "Daska:Gultan": 1154,
  "Gultan:Gujranwala": 1434,
  "Gujranwala:Gultan": 1434,
  "Gultan:Gujrat": 684,
  "Gujrat:Gultan": 684,
  "Gultan:Hyderabad": 1437,
  "Hyderabad:Gultan": 1437,
  "Gultan:Jhang": 1436,
  "Jhang:Gultan": 1436,
  "Gultan:Jhelum": 1413,
  "Jhelum:Gultan": 1413,
  "Gultan:Ranipur": 91,
  "Ranipur:Gultan": 91,
  "Gultan:Karachi": 128,
  "Karachi:Gultan": 128,
  "Gultan:Karachi Cantt": 1424,
  "Karachi Cantt:Gultan": 1424,
  "Gultan:Kohat": 469,
  "Kohat:Gultan": 469,
  "Gultan:Murree": 475,
  "Murree:Gultan": 475,
  "Gultan:Okara Cantt": 1291,
  "Okara Cantt:Gultan": 1291,
  "Gultan:Okara City": 1153,
  "Okara City:Gultan": 1153,
  "Gultan:Sahiwal": 1222,
  "Sahiwal:Gultan": 1222,
  "Gultan:Multan": 887,
  "Multan:Gultan": 887,
  "Gultan:Vehari Chowk": 150,
  "Vehari Chowk:Gultan": 150,
  "Gultan:Peshawar": 131,
  "Peshawar:Gultan": 131,
  "Gultan:Islamabad": 226,
  "Islamabad:Gultan": 226,
  "Gultan:Quetta": 551,
  "Quetta:Gultan": 551,
  "Gultan:Sialkot": 380,
  "Sialkot:Gultan": 380,
  "Sargodha:Abbottabad": 1114,
  "Abbottabad:Sargodha": 1114,
  "Sargodha:Faizabad": 1184,
  "Faizabad:Sargodha": 1184,
  "Sargodha:Bahawalpur": 545,
  "Bahawalpur:Sargodha": 545,
  "Sargodha:Hakar Chowk": 1139,
  "Hakar Chowk:Sargodha": 1139,
  "Sargodha:Bahadurpur Chowk": 489,
  "Bahadurpur Chowk:Sargodha": 489,
  "Sargodha:Chichawatni": 1191,
  "Chichawatni:Sargodha": 1191,
  "Sargodha:Daska": 1233,
  "Daska:Sargodha": 1233,
  "Sargodha:Gujranwala": 1260,
  "Gujranwala:Sargodha": 1260,
  "Sargodha:Gujrat": 935,
  "Gujrat:Sargodha": 935,
  "Sargodha:Hyderabad": 1173,
  "Hyderabad:Sargodha": 1173,
  "Sargodha:Jhang": 646,
  "Jhang:Sargodha": 646,
  "Sargodha:Jhelum": 1349,
  "Jhelum:Sargodha": 1349,
  "Sargodha:Ranipur": 155,
  "Ranipur:Sargodha": 155,
  "Sargodha:Karachi": 1046,
  "Karachi:Sargodha": 1046,
  "Sargodha:Karachi Cantt": 869,
  "Karachi Cantt:Sargodha": 869,
  "Sargodha:Kohat": 1296,
  "Kohat:Sargodha": 1296,
  "Sargodha:Murree": 85,
  "Murree:Sargodha": 85,
  "Sargodha:Okara Cantt": 852,
  "Okara Cantt:Sargodha": 852,
  "Sargodha:Okara City": 560,
  "Okara City:Sargodha": 560,
  "Sargodha:Sahiwal": 1219,
  "Sahiwal:Sargodha": 1219,
  "Sargodha:Multan": 445,
  "Multan:Sargodha": 445,
  "Sargodha:Vehari Chowk": 1155,
  "Vehari Chowk:Sargodha": 1155,
  "Sargodha:Peshawar": 386,
  "Peshawar:Sargodha": 386,
  "Sargodha:Islamabad": 1340,
  "Islamabad:Sargodha": 1340,
  "Sargodha:Quetta": 1103,
  "Quetta:Sargodha": 1103,
  "Sargodha:Sialkot": 572,
  "Sialkot:Sargodha": 572,
  "Abbottabad:Faizabad": 582,
  "Faizabad:Abbottabad": 582,
  "Abbottabad:Bahawalpur": 1372,
  "Bahawalpur:Abbottabad": 1372,
  "Abbottabad:Hakar Chowk": 247,
  "Hakar Chowk:Abbottabad": 247,
  "Abbottabad:Bahadurpur Chowk": 654,
  "Bahadurpur Chowk:Abbottabad": 654,
  "Abbottabad:Chichawatni": 272,
  "Chichawatni:Abbottabad": 272,
  "Abbottabad:Daska": 925,
  "Daska:Abbottabad": 925,
  "Abbottabad:Gujranwala": 992,
  "Gujranwala:Abbottabad": 992,
  "Abbottabad:Gujrat": 1195,
  "Gujrat:Abbottabad": 1195,
  "Abbottabad:Hyderabad": 1205,
  "Hyderabad:Abbottabad": 1205,
  "Abbottabad:Jhang": 1462,
  "Jhang:Abbottabad": 1462,
  "Abbottabad:Jhelum": 1245,
  "Jhelum:Abbottabad": 1245,
  "Abbottabad:Ranipur": 1196,
  "Ranipur:Abbottabad": 1196,
  "Abbottabad:Karachi": 582,
  "Karachi:Abbottabad": 582,
  "Abbottabad:Karachi Cantt": 781,
  "Karachi Cantt:Abbottabad": 781,
  "Abbottabad:Kohat": 1142,
  "Kohat:Abbottabad": 1142,
  "Abbottabad:Murree": 913,
  "Murree:Abbottabad": 913,
  "Abbottabad:Okara Cantt": 751,
  "Okara Cantt:Abbottabad": 751,
  "Abbottabad:Okara City": 1457,
  "Okara City:Abbottabad": 1457,
  "Abbottabad:Sahiwal": 483,
  "Sahiwal:Abbottabad": 483,
  "Abbottabad:Multan": 362,
  "Multan:Abbottabad": 362,
  "Abbottabad:Vehari Chowk": 1164,
  "Vehari Chowk:Abbottabad": 1164,
  "Abbottabad:Peshawar": 1440,
  "Peshawar:Abbottabad": 1440,
  "Abbottabad:Islamabad": 54,
  "Islamabad:Abbottabad": 54,
  "Abbottabad:Quetta": 620,
  "Quetta:Abbottabad": 620,
  "Abbottabad:Sialkot": 981,
  "Sialkot:Abbottabad": 981,
  "Faizabad:Bahawalpur": 1138,
  "Bahawalpur:Faizabad": 1138,
  "Faizabad:Hakar Chowk": 869,
  "Hakar Chowk:Faizabad": 869,
  "Faizabad:Bahadurpur Chowk": 244,
  "Bahadurpur Chowk:Faizabad": 244,
  "Faizabad:Chichawatni": 786,
  "Chichawatni:Faizabad": 786,
  "Faizabad:Daska": 492,
  "Daska:Faizabad": 492,
  "Faizabad:Gujranwala": 472,
  "Gujranwala:Faizabad": 472,
  "Faizabad:Gujrat": 414,
  "Gujrat:Faizabad": 414,
  "Faizabad:Hyderabad": 648,
  "Hyderabad:Faizabad": 648,
  "Faizabad:Jhang": 1017,
  "Jhang:Faizabad": 1017,
  "Faizabad:Jhelum": 601,
  "Jhelum:Faizabad": 601,
  "Faizabad:Ranipur": 1125,
  "Ranipur:Faizabad": 1125,
  "Faizabad:Karachi": 593,
  "Karachi:Faizabad": 593,
  "Faizabad:Karachi Cantt": 791,
  "Karachi Cantt:Faizabad": 791,
  "Faizabad:Kohat": 1137,
  "Kohat:Faizabad": 1137,
  "Faizabad:Murree": 1221,
  "Murree:Faizabad": 1221,
  "Faizabad:Okara Cantt": 1487,
  "Okara Cantt:Faizabad": 1487,
  "Faizabad:Okara City": 456,
  "Okara City:Faizabad": 456,
  "Faizabad:Sahiwal": 1481,
  "Sahiwal:Faizabad": 1481,
  "Faizabad:Multan": 984,
  "Multan:Faizabad": 984,
  "Faizabad:Vehari Chowk": 619,
  "Vehari Chowk:Faizabad": 619,
  "Faizabad:Peshawar": 757,
  "Peshawar:Faizabad": 757,
  "Faizabad:Islamabad": 263,
  "Islamabad:Faizabad": 263,
  "Faizabad:Quetta": 432,
  "Quetta:Faizabad": 432,
  "Faizabad:Sialkot": 401,
  "Sialkot:Faizabad": 401,
  "Bahawalpur:Hakar Chowk": 133,
  "Hakar Chowk:Bahawalpur": 133,
  "Bahawalpur:Bahadurpur Chowk": 1299,
  "Bahadurpur Chowk:Bahawalpur": 1299,
  "Bahawalpur:Chichawatni": 931,
  "Chichawatni:Bahawalpur": 931,
  "Bahawalpur:Daska": 1248,
  "Daska:Bahawalpur": 1248,
  "Bahawalpur:Gujranwala": 1253,
  "Gujranwala:Bahawalpur": 1253,
  "Bahawalpur:Gujrat": 189,
  "Gujrat:Bahawalpur": 189,
  "Bahawalpur:Hyderabad": 865,
  "Hyderabad:Bahawalpur": 865,
  "Bahawalpur:Jhang": 474,
  "Jhang:Bahawalpur": 474,
  "Bahawalpur:Jhelum": 1181,
  "Jhelum:Bahawalpur": 1181,
  "Bahawalpur:Ranipur": 1211,
  "Ranipur:Bahawalpur": 1211,
  "Bahawalpur:Karachi": 1323,
  "Karachi:Bahawalpur": 1323,
  "Bahawalpur:Karachi Cantt": 1415,
  "Karachi Cantt:Bahawalpur": 1415,
  "Bahawalpur:Kohat": 856,
  "Kohat:Bahawalpur": 856,
  "Bahawalpur:Murree": 618,
  "Murree:Bahawalpur": 618,
  "Bahawalpur:Okara Cantt": 426,
  "Okara Cantt:Bahawalpur": 426,
  "Bahawalpur:Okara City": 737,
  "Okara City:Bahawalpur": 737,
  "Bahawalpur:Sahiwal": 95,
  "Sahiwal:Bahawalpur": 95,
  "Bahawalpur:Multan": 1064,
  "Multan:Bahawalpur": 1064,
  "Bahawalpur:Vehari Chowk": 1447,
  "Vehari Chowk:Bahawalpur": 1447,
  "Bahawalpur:Peshawar": 403,
  "Peshawar:Bahawalpur": 403,
  "Bahawalpur:Islamabad": 1237,
  "Islamabad:Bahawalpur": 1237,
  "Bahawalpur:Quetta": 588,
  "Quetta:Bahawalpur": 588,
  "Bahawalpur:Sialkot": 1147,
  "Sialkot:Bahawalpur": 1147,
  "Hakar Chowk:Bahadurpur Chowk": 973,
  "Bahadurpur Chowk:Hakar Chowk": 973,
  "Hakar Chowk:Chichawatni": 1078,
  "Chichawatni:Hakar Chowk": 1078,
  "Hakar Chowk:Daska": 1119,
  "Daska:Hakar Chowk": 1119,
  "Hakar Chowk:Gujranwala": 1286,
  "Gujranwala:Hakar Chowk": 1286,
  "Hakar Chowk:Gujrat": 121,
  "Gujrat:Hakar Chowk": 121,
  "Hakar Chowk:Hyderabad": 847,
  "Hyderabad:Hakar Chowk": 847,
  "Hakar Chowk:Jhang": 249,
  "Jhang:Hakar Chowk": 249,
  "Hakar Chowk:Jhelum": 680,
  "Jhelum:Hakar Chowk": 680,
  "Hakar Chowk:Ranipur": 1129,
  "Ranipur:Hakar Chowk": 1129,
  "Hakar Chowk:Karachi": 1306,
  "Karachi:Hakar Chowk": 1306,
  "Hakar Chowk:Karachi Cantt": 504,
  "Karachi Cantt:Hakar Chowk": 504,
  "Hakar Chowk:Kohat": 65,
  "Kohat:Hakar Chowk": 65,
  "Hakar Chowk:Murree": 686,
  "Murree:Hakar Chowk": 686,
  "Hakar Chowk:Okara Cantt": 633,
  "Okara Cantt:Hakar Chowk": 633,
  "Hakar Chowk:Okara City": 1437,
  "Okara City:Hakar Chowk": 1437,
  "Hakar Chowk:Sahiwal": 282,
  "Sahiwal:Hakar Chowk": 282,
  "Hakar Chowk:Multan": 859,
  "Multan:Hakar Chowk": 859,
  "Hakar Chowk:Vehari Chowk": 905,
  "Vehari Chowk:Hakar Chowk": 905,
  "Hakar Chowk:Peshawar": 1209,
  "Peshawar:Hakar Chowk": 1209,
  "Hakar Chowk:Islamabad": 1487,
  "Islamabad:Hakar Chowk": 1487,
  "Hakar Chowk:Quetta": 255,
  "Quetta:Hakar Chowk": 255,
  "Hakar Chowk:Sialkot": 498,
  "Sialkot:Hakar Chowk": 498,
  "Bahadurpur Chowk:Chichawatni": 1295,
  "Chichawatni:Bahadurpur Chowk": 1295,
  "Bahadurpur Chowk:Daska": 471,
  "Daska:Bahadurpur Chowk": 471,
  "Bahadurpur Chowk:Gujranwala": 577,
  "Gujranwala:Bahadurpur Chowk": 577,
  "Bahadurpur Chowk:Gujrat": 1072,
  "Gujrat:Bahadurpur Chowk": 1072,
  "Bahadurpur Chowk:Hyderabad": 1498,
  "Hyderabad:Bahadurpur Chowk": 1498,
  "Bahadurpur Chowk:Jhang": 1470,
  "Jhang:Bahadurpur Chowk": 1470,
  "Bahadurpur Chowk:Jhelum": 1152,
  "Jhelum:Bahadurpur Chowk": 1152,
  "Bahadurpur Chowk:Ranipur": 314,
  "Ranipur:Bahadurpur Chowk": 314,
  "Bahadurpur Chowk:Karachi": 971,
  "Karachi:Bahadurpur Chowk": 971,
  "Bahadurpur Chowk:Karachi Cantt": 524,
  "Karachi Cantt:Bahadurpur Chowk": 524,
  "Bahadurpur Chowk:Kohat": 452,
  "Kohat:Bahadurpur Chowk": 452,
  "Bahadurpur Chowk:Murree": 187,
  "Murree:Bahadurpur Chowk": 187,
  "Bahadurpur Chowk:Okara Cantt": 1247,
  "Okara Cantt:Bahadurpur Chowk": 1247,
  "Bahadurpur Chowk:Okara City": 171,
  "Okara City:Bahadurpur Chowk": 171,
  "Bahadurpur Chowk:Sahiwal": 1171,
  "Sahiwal:Bahadurpur Chowk": 1171,
  "Bahadurpur Chowk:Multan": 1290,
  "Multan:Bahadurpur Chowk": 1290,
  "Bahadurpur Chowk:Vehari Chowk": 576,
  "Vehari Chowk:Bahadurpur Chowk": 576,
  "Bahadurpur Chowk:Peshawar": 182,
  "Peshawar:Bahadurpur Chowk": 182,
  "Bahadurpur Chowk:Islamabad": 881,
  "Islamabad:Bahadurpur Chowk": 881,
  "Bahadurpur Chowk:Quetta": 1299,
  "Quetta:Bahadurpur Chowk": 1299,
  "Bahadurpur Chowk:Sialkot": 726,
  "Sialkot:Bahadurpur Chowk": 726,
  "Chichawatni:Daska": 325,
  "Daska:Chichawatni": 325,
  "Chichawatni:Gujranwala": 116,
  "Gujranwala:Chichawatni": 116,
  "Chichawatni:Gujrat": 70,
  "Gujrat:Chichawatni": 70,
  "Chichawatni:Hyderabad": 821,
  "Hyderabad:Chichawatni": 821,
  "Chichawatni:Jhang": 195,
  "Jhang:Chichawatni": 195,
  "Chichawatni:Jhelum": 597,
  "Jhelum:Chichawatni": 597,
  "Chichawatni:Ranipur": 163,
  "Ranipur:Chichawatni": 163,
  "Chichawatni:Karachi": 554,
  "Karachi:Chichawatni": 554,
  "Chichawatni:Karachi Cantt": 1127,
  "Karachi Cantt:Chichawatni": 1127,
  "Chichawatni:Kohat": 466,
  "Kohat:Chichawatni": 466,
  "Chichawatni:Murree": 528,
  "Murree:Chichawatni": 528,
  "Chichawatni:Okara Cantt": 1030,
  "Okara Cantt:Chichawatni": 1030,
  "Chichawatni:Okara City": 1210,
  "Okara City:Chichawatni": 1210,
  "Chichawatni:Sahiwal": 751,
  "Sahiwal:Chichawatni": 751,
  "Chichawatni:Multan": 1338,
  "Multan:Chichawatni": 1338,
  "Chichawatni:Vehari Chowk": 1261,
  "Vehari Chowk:Chichawatni": 1261,
  "Chichawatni:Peshawar": 543,
  "Peshawar:Chichawatni": 543,
  "Chichawatni:Islamabad": 1063,
  "Islamabad:Chichawatni": 1063,
  "Chichawatni:Quetta": 417,
  "Quetta:Chichawatni": 417,
  "Chichawatni:Sialkot": 692,
  "Sialkot:Chichawatni": 692,
  "Daska:Gujranwala": 366,
  "Gujranwala:Daska": 366,
  "Daska:Gujrat": 727,
  "Gujrat:Daska": 727,
  "Daska:Hyderabad": 1210,
  "Hyderabad:Daska": 1210,
  "Daska:Jhang": 1220,
  "Jhang:Daska": 1220,
  "Daska:Jhelum": 1425,
  "Jhelum:Daska": 1425,
  "Daska:Ranipur": 419,
  "Ranipur:Daska": 419,
  "Daska:Karachi": 690,
  "Karachi:Daska": 690,
  "Daska:Karachi Cantt": 285,
  "Karachi Cantt:Daska": 285,
  "Daska:Kohat": 559,
  "Kohat:Daska": 559,
  "Daska:Murree": 1083,
  "Murree:Daska": 1083,
  "Daska:Okara Cantt": 497,
  "Okara Cantt:Daska": 497,
  "Daska:Okara City": 1475,
  "Okara City:Daska": 1475,
  "Daska:Sahiwal": 1089,
  "Sahiwal:Daska": 1089,
  "Daska:Multan": 1116,
  "Multan:Daska": 1116,
  "Daska:Vehari Chowk": 784,
  "Vehari Chowk:Daska": 784,
  "Daska:Peshawar": 475,
  "Peshawar:Daska": 475,
  "Daska:Islamabad": 1258,
  "Islamabad:Daska": 1258,
  "Daska:Quetta": 257,
  "Quetta:Daska": 257,
  "Daska:Sialkot": 904,
  "Sialkot:Daska": 904,
  "Gujranwala:Gujrat": 1298,
  "Gujrat:Gujranwala": 1298,
  "Gujranwala:Hyderabad": 884,
  "Hyderabad:Gujranwala": 884,
  "Gujranwala:Jhang": 271,
  "Jhang:Gujranwala": 271,
  "Gujranwala:Jhelum": 371,
  "Jhelum:Gujranwala": 371,
  "Gujranwala:Ranipur": 117,
  "Ranipur:Gujranwala": 117,
  "Gujranwala:Karachi": 167,
  "Karachi:Gujranwala": 167,
  "Gujranwala:Karachi Cantt": 723,
  "Karachi Cantt:Gujranwala": 723,
  "Gujranwala:Kohat": 776,
  "Kohat:Gujranwala": 776,
  "Gujranwala:Murree": 656,
  "Murree:Gujranwala": 656,
  "Gujranwala:Okara Cantt": 234,
  "Okara Cantt:Gujranwala": 234,
  "Gujranwala:Okara City": 125,
  "Okara City:Gujranwala": 125,
  "Gujranwala:Sahiwal": 261,
  "Sahiwal:Gujranwala": 261,
  "Gujranwala:Multan": 1078,
  "Multan:Gujranwala": 1078,
  "Gujranwala:Vehari Chowk": 898,
  "Vehari Chowk:Gujranwala": 898,
  "Gujranwala:Peshawar": 1162,
  "Peshawar:Gujranwala": 1162,
  "Gujranwala:Islamabad": 259,
  "Islamabad:Gujranwala": 259,
  "Gujranwala:Quetta": 902,
  "Quetta:Gujranwala": 902,
  "Gujranwala:Sialkot": 1361,
  "Sialkot:Gujranwala": 1361,
  "Gujrat:Hyderabad": 84,
  "Hyderabad:Gujrat": 84,
  "Gujrat:Jhang": 992,
  "Jhang:Gujrat": 992,
  "Gujrat:Jhelum": 1391,
  "Jhelum:Gujrat": 1391,
  "Gujrat:Ranipur": 510,
  "Ranipur:Gujrat": 510,
  "Gujrat:Karachi": 727,
  "Karachi:Gujrat": 727,
  "Gujrat:Karachi Cantt": 808,
  "Karachi Cantt:Gujrat": 808,
  "Gujrat:Kohat": 296,
  "Kohat:Gujrat": 296,
  "Gujrat:Murree": 548,
  "Murree:Gujrat": 548,
  "Gujrat:Okara Cantt": 1216,
  "Okara Cantt:Gujrat": 1216,
  "Gujrat:Okara City": 871,
  "Okara City:Gujrat": 871,
  "Gujrat:Sahiwal": 98,
  "Sahiwal:Gujrat": 98,
  "Gujrat:Multan": 362,
  "Multan:Gujrat": 362,
  "Gujrat:Vehari Chowk": 1184,
  "Vehari Chowk:Gujrat": 1184,
  "Gujrat:Peshawar": 787,
  "Peshawar:Gujrat": 787,
  "Gujrat:Islamabad": 1481,
  "Islamabad:Gujrat": 1481,
  "Gujrat:Quetta": 995,
  "Quetta:Gujrat": 995,
  "Gujrat:Sialkot": 307,
  "Sialkot:Gujrat": 307,
  "Hyderabad:Jhang": 1049,
  "Jhang:Hyderabad": 1049,
  "Hyderabad:Jhelum": 939,
  "Jhelum:Hyderabad": 939,
  "Hyderabad:Ranipur": 892,
  "Ranipur:Hyderabad": 892,
  "Hyderabad:Karachi": 842,
  "Karachi:Hyderabad": 842,
  "Hyderabad:Karachi Cantt": 1245,
  "Karachi Cantt:Hyderabad": 1245,
  "Hyderabad:Kohat": 1430,
  "Kohat:Hyderabad": 1430,
  "Hyderabad:Murree": 840,
  "Murree:Hyderabad": 840,
  "Hyderabad:Okara Cantt": 1140,
  "Okara Cantt:Hyderabad": 1140,
  "Hyderabad:Okara City": 228,
  "Okara City:Hyderabad": 228,
  "Hyderabad:Sahiwal": 1191,
  "Sahiwal:Hyderabad": 1191,
  "Hyderabad:Multan": 804,
  "Multan:Hyderabad": 804,
  "Hyderabad:Vehari Chowk": 1038,
  "Vehari Chowk:Hyderabad": 1038,
  "Hyderabad:Peshawar": 333,
  "Peshawar:Hyderabad": 333,
  "Hyderabad:Islamabad": 625,
  "Islamabad:Hyderabad": 625,
  "Hyderabad:Quetta": 82,
  "Quetta:Hyderabad": 82,
  "Hyderabad:Sialkot": 1044,
  "Sialkot:Hyderabad": 1044,
  "Jhang:Jhelum": 70,
  "Jhelum:Jhang": 70,
  "Jhang:Ranipur": 342,
  "Ranipur:Jhang": 342,
  "Jhang:Karachi": 957,
  "Karachi:Jhang": 957,
  "Jhang:Karachi Cantt": 86,
  "Karachi Cantt:Jhang": 86,
  "Jhang:Kohat": 108,
  "Kohat:Jhang": 108,
  "Jhang:Murree": 776,
  "Murree:Jhang": 776,
  "Jhang:Okara Cantt": 208,
  "Okara Cantt:Jhang": 208,
  "Jhang:Okara City": 963,
  "Okara City:Jhang": 963,
  "Jhang:Sahiwal": 1017,
  "Sahiwal:Jhang": 1017,
  "Jhang:Multan": 398,
  "Multan:Jhang": 398,
  "Jhang:Vehari Chowk": 443,
  "Vehari Chowk:Jhang": 443,
  "Jhang:Peshawar": 1498,
  "Peshawar:Jhang": 1498,
  "Jhang:Islamabad": 758,
  "Islamabad:Jhang": 758,
  "Jhang:Quetta": 1253,
  "Quetta:Jhang": 1253,
  "Jhang:Sialkot": 1308,
  "Sialkot:Jhang": 1308,
  "Jhelum:Ranipur": 727,
  "Ranipur:Jhelum": 727,
  "Jhelum:Karachi": 983,
  "Karachi:Jhelum": 983,
  "Jhelum:Karachi Cantt": 216,
  "Karachi Cantt:Jhelum": 216,
  "Jhelum:Kohat": 350,
  "Kohat:Jhelum": 350,
  "Jhelum:Murree": 1442,
  "Murree:Jhelum": 1442,
  "Jhelum:Okara Cantt": 1162,
  "Okara Cantt:Jhelum": 1162,
  "Jhelum:Okara City": 193,
  "Okara City:Jhelum": 193,
  "Jhelum:Sahiwal": 637,
  "Sahiwal:Jhelum": 637,
  "Jhelum:Multan": 1119,
  "Multan:Jhelum": 1119,
  "Jhelum:Vehari Chowk": 261,
  "Vehari Chowk:Jhelum": 261,
  "Jhelum:Peshawar": 1327,
  "Peshawar:Jhelum": 1327,
  "Jhelum:Islamabad": 734,
  "Islamabad:Jhelum": 734,
  "Jhelum:Quetta": 1082,
  "Quetta:Jhelum": 1082,
  "Jhelum:Sialkot": 1347,
  "Sialkot:Jhelum": 1347,
  "Ranipur:Karachi": 320,
  "Karachi:Ranipur": 320,
  "Ranipur:Karachi Cantt": 983,
  "Karachi Cantt:Ranipur": 983,
  "Ranipur:Kohat": 709,
  "Kohat:Ranipur": 709,
  "Ranipur:Murree": 1199,
  "Murree:Ranipur": 1199,
  "Ranipur:Okara Cantt": 1363,
  "Okara Cantt:Ranipur": 1363,
  "Ranipur:Okara City": 1007,
  "Okara City:Ranipur": 1007,
  "Ranipur:Sahiwal": 974,
  "Sahiwal:Ranipur": 974,
  "Ranipur:Multan": 584,
  "Multan:Ranipur": 584,
  "Ranipur:Vehari Chowk": 1092,
  "Vehari Chowk:Ranipur": 1092,
  "Ranipur:Peshawar": 563,
  "Peshawar:Ranipur": 563,
  "Ranipur:Islamabad": 1453,
  "Islamabad:Ranipur": 1453,
  "Ranipur:Quetta": 432,
  "Quetta:Ranipur": 432,
  "Ranipur:Sialkot": 114,
  "Sialkot:Ranipur": 114,
  "Karachi:Karachi Cantt": 966,
  "Karachi Cantt:Karachi": 966,
  "Karachi:Kohat": 1208,
  "Kohat:Karachi": 1208,
  "Karachi:Murree": 121,
  "Murree:Karachi": 121,
  "Karachi:Okara Cantt": 1407,
  "Okara Cantt:Karachi": 1407,
  "Karachi:Okara City": 1058,
  "Okara City:Karachi": 1058,
  "Karachi:Sahiwal": 655,
  "Sahiwal:Karachi": 655,
  "Karachi:Multan": 1080,
  "Multan:Karachi": 1080,
  "Karachi:Vehari Chowk": 1050,
  "Vehari Chowk:Karachi": 1050,
  "Karachi:Peshawar": 1488,
  "Peshawar:Karachi": 1488,
  "Karachi:Islamabad": 241,
  "Islamabad:Karachi": 241,
  "Karachi:Quetta": 891,
  "Quetta:Karachi": 891,
  "Karachi:Sialkot": 1056,
  "Sialkot:Karachi": 1056,
  "Karachi Cantt:Kohat": 961,
  "Kohat:Karachi Cantt": 961,
  "Karachi Cantt:Murree": 1199,
  "Murree:Karachi Cantt": 1199,
  "Karachi Cantt:Okara Cantt": 488,
  "Okara Cantt:Karachi Cantt": 488,
  "Karachi Cantt:Okara City": 435,
  "Okara City:Karachi Cantt": 435,
  "Karachi Cantt:Sahiwal": 1171,
  "Sahiwal:Karachi Cantt": 1171,
  "Karachi Cantt:Multan": 659,
  "Multan:Karachi Cantt": 659,
  "Karachi Cantt:Vehari Chowk": 1100,
  "Vehari Chowk:Karachi Cantt": 1100,
  "Karachi Cantt:Peshawar": 907,
  "Peshawar:Karachi Cantt": 907,
  "Karachi Cantt:Islamabad": 681,
  "Islamabad:Karachi Cantt": 681,
  "Karachi Cantt:Quetta": 1221,
  "Quetta:Karachi Cantt": 1221,
  "Karachi Cantt:Sialkot": 1021,
  "Sialkot:Karachi Cantt": 1021,
  "Kohat:Murree": 953,
  "Murree:Kohat": 953,
  "Kohat:Okara Cantt": 1325,
  "Okara Cantt:Kohat": 1325,
  "Kohat:Okara City": 390,
  "Okara City:Kohat": 390,
  "Kohat:Sahiwal": 133,
  "Sahiwal:Kohat": 133,
  "Kohat:Multan": 135,
  "Multan:Kohat": 135,
  "Kohat:Vehari Chowk": 287,
  "Vehari Chowk:Kohat": 287,
  "Kohat:Peshawar": 502,
  "Peshawar:Kohat": 502,
  "Kohat:Islamabad": 1065,
  "Islamabad:Kohat": 1065,
  "Kohat:Quetta": 106,
  "Quetta:Kohat": 106,
  "Kohat:Sialkot": 958,
  "Sialkot:Kohat": 958,
  "Murree:Okara Cantt": 841,
  "Okara Cantt:Murree": 841,
  "Murree:Okara City": 1442,
  "Okara City:Murree": 1442,
  "Murree:Sahiwal": 244,
  "Sahiwal:Murree": 244,
  "Murree:Multan": 1258,
  "Multan:Murree": 1258,
  "Murree:Vehari Chowk": 202,
  "Vehari Chowk:Murree": 202,
  "Murree:Peshawar": 1208,
  "Peshawar:Murree": 1208,
  "Murree:Islamabad": 359,
  "Islamabad:Murree": 359,
  "Murree:Quetta": 392,
  "Quetta:Murree": 392,
  "Murree:Sialkot": 121,
  "Sialkot:Murree": 121,
  "Okara Cantt:Okara City": 1441,
  "Okara City:Okara Cantt": 1441,
  "Okara Cantt:Sahiwal": 664,
  "Sahiwal:Okara Cantt": 664,
  "Okara Cantt:Multan": 641,
  "Multan:Okara Cantt": 641,
  "Okara Cantt:Vehari Chowk": 1234,
  "Vehari Chowk:Okara Cantt": 1234,
  "Okara Cantt:Peshawar": 1396,
  "Peshawar:Okara Cantt": 1396,
  "Okara Cantt:Islamabad": 1208,
  "Islamabad:Okara Cantt": 1208,
  "Okara Cantt:Quetta": 833,
  "Quetta:Okara Cantt": 833,
  "Okara Cantt:Sialkot": 412,
  "Sialkot:Okara Cantt": 412,
  "Okara City:Sahiwal": 718,
  "Sahiwal:Okara City": 718,
  "Okara City:Multan": 1420,
  "Multan:Okara City": 1420,
  "Okara City:Vehari Chowk": 1225,
  "Vehari Chowk:Okara City": 1225,
  "Okara City:Peshawar": 347,
  "Peshawar:Okara City": 347,
  "Okara City:Islamabad": 545,
  "Islamabad:Okara City": 545,
  "Okara City:Quetta": 1119,
  "Quetta:Okara City": 1119,
  "Okara City:Sialkot": 439,
  "Sialkot:Okara City": 439,
  "Sahiwal:Multan": 942,
  "Multan:Sahiwal": 942,
  "Sahiwal:Vehari Chowk": 936,
  "Vehari Chowk:Sahiwal": 936,
  "Sahiwal:Peshawar": 407,
  "Peshawar:Sahiwal": 407,
  "Sahiwal:Islamabad": 788,
  "Islamabad:Sahiwal": 788,
  "Sahiwal:Quetta": 1070,
  "Quetta:Sahiwal": 1070,
  "Sahiwal:Sialkot": 1426,
  "Sialkot:Sahiwal": 1426,
  "Multan:Vehari Chowk": 867,
  "Vehari Chowk:Multan": 867,
  "Multan:Peshawar": 50,
  "Peshawar:Multan": 50,
  "Multan:Islamabad": 1150,
  "Islamabad:Multan": 1150,
  "Multan:Quetta": 134,
  "Quetta:Multan": 134,
  "Multan:Sialkot": 687,
  "Sialkot:Multan": 687,
  "Vehari Chowk:Peshawar": 1401,
  "Peshawar:Vehari Chowk": 1401,
  "Vehari Chowk:Islamabad": 448,
  "Islamabad:Vehari Chowk": 448,
  "Vehari Chowk:Quetta": 862,
  "Quetta:Vehari Chowk": 862,
  "Vehari Chowk:Sialkot": 1034,
  "Sialkot:Vehari Chowk": 1034,
  "Peshawar:Islamabad": 611,
  "Islamabad:Peshawar": 611,
  "Peshawar:Quetta": 171,
  "Quetta:Peshawar": 171,
  "Peshawar:Sialkot": 570,
  "Sialkot:Peshawar": 570,
  "Islamabad:Quetta": 126,
  "Quetta:Islamabad": 126,
  "Islamabad:Sialkot": 950,
  "Sialkot:Islamabad": 950,
  "Quetta:Sialkot": 597,
  "Sialkot:Quetta": 597,
};

const farePerKm = 5;

app.set("view engine", "ejs");
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, "public")));

function isLoggedIn(req, res, next) {
  if (!req.cookies.token || req.cookies.token === "") {
    return res.redirect("/login");
  } else {
    try {
      let data = jwt.verify(req.cookies.token, "shhhh");
      req.user = data;
      next();
    } catch (err) {
      return res.redirect("/login");
    }
  }
}

app.get("/travel", (req, res) => res.render("travel"));
app.get("/signup", (req, res) => res.render("signup"));
app.get("/login", (req, res) => res.render("login"));
app.get("/booking", (req, res) => res.render("booking"));

app.get("/select-seat", isLoggedIn, (req, res) => {
  const { from, to, date } = req.query;
  res.render("selectSeat", { from: from || "", to: to || "", date: date || "" });
});

app.post("/register", async (req, res) => {
  const { name, password, username, email, age } = req.body;
  const existingUser = await userModel.findOne({ email });
  if (existingUser) return res.status(400).send("User already registered");

  const salt = await bcrypt.genSalt(10);
  const hash = await bcrypt.hash(password, salt);

  const user = await userModel.create({ username, email, age, name, password: hash });
  const token = jwt.sign({ email: email, userid: user._id }, "shhhh");

  res.cookie("token", token);
  res.redirect("/booking");
});

app.post("/login", async (req, res) => {
  const { email, password } = req.body;
  const user = await userModel.findOne({ email });
  if (!user) return res.status(400).send("User not found");

  const result = await bcrypt.compare(password, user.password);
  if (result) {
    const token = jwt.sign({ email: user.email, userid: user._id }, "shhhh");
    res.cookie("token", token);
    return res.status(200).redirect("/booking");
  } else {
    return res.status(401).send("Incorrect password");
  }
});

app.post("/select-seat", isLoggedIn, (req, res) => {
  const { from, to, date } = req.body;
  res.redirect(`/select-seat?from=${from}&to=${to}&date=${date}`);
});

app.post("/book-seat", isLoggedIn, async (req, res) => {
  const { seats, time, from, to, date } = req.body;
  const userData = req.user;
  const selectedSeats = Array.isArray(seats) ? seats.map(Number) : [Number(seats)];

  const key1 = `${from}:${to}`;
  const key2 = `${to}:${from}`;
  const distance = distances[key1] || distances[key2] || 0;
  const rentPerSeat = distance * farePerKm;

  // Create separate booking for each seat
  for (const seat of selectedSeats) {
    await postModel.create({
      user: userData.userid,
      total_seats: 1,  // Each booking is for 1 seat
      time,
      seats: [seat],    // Store seat as array with single element
      from,
      to,
      date,
      distance,
      fare: rentPerSeat,
    });
  }

  const bookings = await postModel.find({ user: userData.userid });
  res.render("tickets", { bookings });
});

app.get("/tickets", isLoggedIn, async (req, res) => {
  try {
    const bookings = await postModel.find({ user: req.user.userid });
    res.render("tickets", { bookings });
  } catch (err) {
    res.status(500).send("Error loading bookings");
  }
});

app.delete("/api/cancel-seat/:bookingId/:seatNo", isLoggedIn, async (req, res) => {
  const { bookingId, seatNo } = req.params;

  try {
    const booking = await postModel.findById(bookingId);
    if (!booking) {
      return res.status(404).json({ error: "Booking not found" });
    }

    const seat = Number(seatNo);
    // Remove the cancelled seat
    booking.seats = booking.seats.filter(s => s !== seat);
    booking.total_seats = booking.seats.length;
    booking.fare = booking.total_seats * (booking.distance * farePerKm);

    if (booking.seats.length === 0) {
      // Delete booking if no seats left
      await postModel.findByIdAndDelete(bookingId);
    } else {
      await booking.save();
    }

    // Now get the latest bookings list AFTER DB update
    const updatedBookings = await postModel.find({ user: req.user.userid });

    res.json({
      message: "Seat cancelled successfully",
      bookings: updatedBookings
    });

  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Server error" });
  }
});




app.listen(3000, () => console.log("Server running on http://localhost:3000"));
